# Simple KNX TP Example Configuration for ESPHome
# This example shows a minimal configuration for testing the KNX TP component

substitutions:
  device_name: knx-test-simple
  friendly_name: "KNX Test Simple"

esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG

# WiFi configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case WiFi connection fails
  ap:
    ssid: "${device_name}-fallback"
    password: !secret ap_password

# UART for KNX TP transceiver (e.g., TPUART, NCN5120, Siemens BCU)
# Common pin configurations:
# - GPIO16 (RX) and GPIO17 (TX) for ESP32
uart:
  id: knx_uart
  tx_pin: GPIO17
  rx_pin: GPIO16
  baud_rate: 19200
  parity: EVEN
  stop_bits: 1

# External KNX TP component
external_components:
  - source:
      type: local
      path: ../components
    components: [ knx_tp ]

# KNX TP Component Configuration
knx_tp:
  # Your KNX physical address (format: area.line.device or area/line/device)
  # Example: 1.1.100 means Area 1, Line 1, Device 100
  physical_address: "1.1.100"
  uart_id: knx_uart

  # Define group addresses to use
  group_addresses:
    # Simple light control
    - id: test_light
      address: "0/0/1"

    # Temperature sensor
    - id: room_temp
      address: "1/0/1"

# Simple binary sensor (reads KNX telegrams)
binary_sensor:
  - platform: knx_tp
    name: "Test Motion Sensor"
    state_ga: test_light
    device_class: motion

# Simple switch (sends KNX telegrams)
switch:
  - platform: knx_tp
    name: "Test Light Switch"
    command_ga: test_light
    icon: "mdi:lightbulb"

# Simple sensor (temperature)
sensor:
  - platform: knx_tp
    name: "Room Temperature"
    state_ga: room_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement
