# ESPHome KNX Configuration for ESP32-S3 N16R8
# 16MB Flash + 8MB PSRAM - Full Featured Example

# Load KNX components from local directory
external_components:
  - source:
      type: local
      path: ../components
    components: [ knx_tp ]

esphome:
  name: knx-gateway-s3
  friendly_name: "KNX Gateway ESP32-S3"
  comment: "Full-featured KNX gateway optimized for ESP32-S3 with 16MB flash"
  platformio_options:
    board_build.flash_mode: qio
    board_build.flash_size: 16MB
    board_build.psram_type: opi
    board_build.memory_type: qio_opi

esp32:
  board: esp32-s3-devkitc-1
  variant: esp32s3
  framework:
    type: esp-idf
  # Note: ESP32-S3-N16R8 features are automatically detected:
  # - 16MB Flash support (vs default 4MB)
  # - 8MB PSRAM (Octal SPI)
  # - Hardware AES/SHA acceleration
  # - 240MHz CPU frequency
  # These are configured automatically by the framework

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: none
  ap:
    ssid: "KNX-Gateway-S3-AP"
    password: !secret ap_password

# Enhanced logging (with more buffer for 16MB flash)
logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: UART0
  logs:
    knx_tp: DEBUG
    component: INFO
    sensor: INFO
    binary_sensor: INFO

# API with encryption
api:
  encryption:
    key: !secret api_encryption_key

# OTA updates
ota:
  - platform: esphome
    password: !secret ota_password

# Web server (more features with 16MB flash)
web_server:
  port: 80
  version: 2
  include_internal: true

# Time source for broadcasts
time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Rome
    servers:
      - 0.pool.ntp.org
      - time.google.com

# I2C bus for sensors
i2c:
  sda: GPIO8
  scl: GPIO9
  scan: true
  frequency: 400kHz

# Status LED
status_led:
  pin:
    number: GPIO48  # Built-in RGB LED on S3
    inverted: false

# ==============================================================================
# KNX-TP Configuration
# ==============================================================================
knx_tp:
  physical_address: "1.1.200"
  uart_id: knx_uart

  # Define all group addresses
  group_addresses:
    # Switches / Lights
    - id: ga_switch_living_room
      address: "1/0/1"

    - id: ga_switch_bedroom
      address: "1/0/2"

    - id: ga_dimmer_living_room
      address: "1/0/3"

    # Sensors
    - id: ga_temperature_living_room
      address: "2/0/1"

    - id: ga_humidity_living_room
      address: "2/0/2"

    - id: ga_temperature_bedroom
      address: "2/0/3"

    - id: ga_pressure
      address: "2/0/4"

    # Binary sensors
    - id: ga_motion_living_room
      address: "3/0/1"

    - id: ga_window_living_room
      address: "3/0/2"

    - id: ga_motion_bedroom
      address: "3/0/3"

    - id: ga_door_main
      address: "3/0/4"

    # Time broadcast
    - id: ga_time
      address: "0/0/1"

  # SAV (Save) pin for Siemens BCU (optional)
  sav_pin:
    number: GPIO3
    inverted: false

# UART for KNX-TP
uart:
  - id: knx_uart
    tx_pin: GPIO1
    rx_pin: GPIO2
    baud_rate: 19200
    parity: EVEN
    data_bits: 8
    stop_bits: 1
    debug:
      direction: BOTH
      dummy_receiver: false
      after:
        timeout: 50ms

# ==============================================================================
# Binary Sensors
# ==============================================================================
binary_sensor:
  # Motion sensors (GPIO)
  - platform: gpio
    id: motion_living_room_local
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: true
    name: "Living Room Motion (Local)"
    device_class: motion

  - platform: gpio
    id: window_living_room_local
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: true
    name: "Living Room Window (Local)"
    device_class: window

  # KNX binary sensors (from bus)
  - platform: knx_tp
    id: motion_bedroom_knx
    name: "Bedroom Motion (KNX)"
    state_ga: ga_motion_bedroom
    device_class: motion

  - platform: knx_tp
    id: door_main_knx
    name: "Main Door (KNX)"
    state_ga: ga_door_main
    device_class: door

# ==============================================================================
# Sensors
# ==============================================================================
sensor:
  # BME280 Temperature/Humidity/Pressure sensor
  - platform: bme280_i2c
    temperature:
      id: temperature_living_room
      name: "Living Room Temperature"
      filters:
        - throttle: 60s
      on_value:
        then:
          - logger.log:
              format: "Temperature: %.1f°C"
              args: [ 'x' ]

    humidity:
      id: humidity_living_room
      name: "Living Room Humidity"
      filters:
        - throttle: 60s

    pressure:
      id: pressure_living_room
      name: "Living Room Pressure"

    address: 0x76
    update_interval: 60s

  # KNX sensors (from bus)
  - platform: knx_tp
    id: temperature_bedroom_knx
    name: "Bedroom Temperature (KNX)"
    state_ga: ga_temperature_bedroom
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature

  # System monitoring
  - platform: uptime
    name: "Uptime"
    update_interval: 60s

  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: internal_temperature
    name: "CPU Temperature"
    update_interval: 60s

  # Memory monitoring (useful with 8MB PSRAM)
  - platform: template
    name: "Free Heap"
    lambda: |-
      #include "esp_heap_caps.h"
      return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 10s
    accuracy_decimals: 0

  - platform: template
    name: "Free PSRAM"
    lambda: |-
      #include "esp_heap_caps.h"
      return heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024.0;
    unit_of_measurement: "kB"
    update_interval: 10s
    accuracy_decimals: 0

# ==============================================================================
# Switches
# ==============================================================================
switch:
  # Physical relay
  - platform: gpio
    id: relay_living_room
    pin: GPIO6
    name: "Living Room Light (Relay)"

  # KNX switches (virtual, control via KNX bus)
  - platform: knx_tp
    id: switch_living_room_knx
    name: "Living Room Light (KNX)"
    command_ga: ga_switch_living_room
    state_ga: ga_switch_living_room
    icon: "mdi:lightbulb"

  - platform: knx_tp
    id: switch_bedroom_knx
    name: "Bedroom Light (KNX)"
    command_ga: ga_switch_bedroom
    state_ga: ga_switch_bedroom
    icon: "mdi:lightbulb"

  # System controls
  - platform: restart
    name: "Restart ESP32-S3"

# ==============================================================================
# Outputs (for PWM dimming)
# ==============================================================================
output:
  - platform: ledc
    id: pwm_output_living_room
    pin: GPIO7
    frequency: 1000 Hz
    channel: 0

# ==============================================================================
# Text Sensors
# ==============================================================================
text_sensor:
  - platform: version
    name: "ESPHome Version"

  - platform: wifi_info
    ip_address:
      name: "IP Address"
    ssid:
      name: "Connected SSID"
    mac_address:
      name: "MAC Address"

  - platform: template
    name: "Chip Model"
    lambda: |-
      return {"ESP32-S3"};
    update_interval: never

  - platform: template
    name: "Flash Size"
    lambda: |-
      return {"16MB"};
    update_interval: never

  - platform: template
    name: "PSRAM Size"
    lambda: |-
      return {"8MB"};
    update_interval: never

# ==============================================================================
# Buttons
# ==============================================================================
button:
  - platform: safe_mode
    name: "Safe Mode Boot"

  - platform: factory_reset
    name: "Factory Reset"
    disabled_by_default: true

# ==============================================================================
# Intervals (Periodic Tasks)
# ==============================================================================
interval:
  # Monitor memory usage every 30 seconds
  - interval: 30s
    then:
      - lambda: |-
          #include "esp_heap_caps.h"
          ESP_LOGD("memory", "Free heap: %d KB, Free PSRAM: %d KB, Largest block: %d KB",
            heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024,
            heap_caps_get_free_size(MALLOC_CAP_SPIRAM) / 1024,
            heap_caps_get_largest_free_block(MALLOC_CAP_INTERNAL) / 1024);

# ==============================================================================
# Notes:
# ==============================================================================
# 1. This configuration is optimized for ESP32-S3-N16R8 (16MB flash, 8MB PSRAM)
# 2. Uses KNX-TP via UART on GPIO1/GPIO2
# 3. Includes BME280 sensor on I2C (GPIO8/GPIO9)
# 4. Extensive logging and monitoring enabled
# 5. Web server for easy access and configuration
# 6. Native USB support (no external USB-UART chip needed)
# 7. Hardware AES/SHA acceleration configured for future KNX Secure
#
# GPIO Usage:
#   GPIO1:  KNX UART TX
#   GPIO2:  KNX UART RX
#   GPIO3:  KNX SAV pin (optional)
#   GPIO4:  Motion sensor input
#   GPIO5:  Window sensor input
#   GPIO6:  Relay output
#   GPIO7:  PWM dimmer output
#   GPIO8:  I2C SDA (BME280)
#   GPIO9:  I2C SCL (BME280)
#   GPIO48: Status LED (WS2812)
#
# Secrets required (secrets.yaml):
#   - wifi_ssid
#   - wifi_password
#   - ap_password
#   - api_encryption_key
#   - ota_password
